# This is a Github Action which, each day:
#   - Uses a node utility (node-gtfs) to pull the latest GTFS database
#   - Compares the latest GTFS database to the current one
#   - If there is a difference, commits the new GTFS database to main, triggering an app update

name: GTFS Database Update Checker
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 4 * * *'
  workflow_dispatch:
jobs:
  GTFS-Check-Update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19.3.x
          cache: 'npm'
          cache-dependency-path: ${{ github.workspace }}/.github/workflows/package-lock.json
      - name: Install node-gtfs
        run: npm install gtfs -g
      - name: Install sqldiff tool
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: sqlite3
      - name: Download latest GTFS database
        run: gtfs-import --gtfsUrl http://www.bart.gov/dev/schedules/google_transit.zip --sqlitePath gtfs_new.db
      - name: See if there is a difference between the current and latest GTFS database
        run: sqldiff gtfs_new.db ${{ github.workspace }}/Shared/gtfs.db 2>&1 | grep "^"
      - name: Update if a difference is detected
        if: ${{ failure() }}
        run: |
          cp gtfs_new.db ${{ github.workspace }}/Shared/gtfs.db
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add ${{ github.workspace }}/Shared/gtfs.db
          git commit -m "Update to latest GTFS database"
          git push origin master
          
        
