# This is a Github Action which, each day:
#   - Uses a node utility (node-gtfs) to pull the latest GTFS database
#   - Uses git to sense if there's any change to the database
#   - If there is a difference, commits the new GTFS database to main, triggering an app update

name: GTFS Database Update Checker
on:
  schedule:
    - cron:  '30 4 * * *'
  workflow_dispatch:
jobs:
  GTFS-Check-Update:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19.3.x
          cache: 'npm'
          cache-dependency-path: ${{ github.workspace }}/.github/workflows/package-lock.json
      - name: Install node-gtfs
        run: npm --prefix ${{ github.workspace }}/.github/workflows install
      - name: Download latest GTFS database
        run: npx --prefix ${{ github.workspace }}/.github/workflows gtfs-import --gtfsUrl http://www.bart.gov/dev/schedules/google_transit.zip --sqlitePath gtfs_new.db
      - name: Replace old DB with new DB
        run: cp gtfs_new.db ${{ github.workspace }}/Shared/gtfs.db
      - name: Commit changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: Shared/gtfs.db
          status_options: '--untracked-files=no'
        
      
        
          
        
